// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ8L3Bi4XHkI4-06t0BoM0tFHhfDPnrwc',
    appId: '1:909338243765:web:f6c89d7a733cd1d92784fc',
    messagingSenderId: '909338243765',
    projectId: 'matsuyama-web',
    authDomain: 'matsuyama-web.firebaseapp.com',
    storageBucket: 'matsuyama-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3PhkVIwNJ2IBqGxul--cNt_t2nGSHbI',
    appId: '1:909338243765:android:3d9c317a2378c6732784fc',
    messagingSenderId: '909338243765',
    projectId: 'matsuyama-web',
    storageBucket: 'matsuyama-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtosuqCL942JB_Zeg40iCLnUCPJiUhL4',
    appId: '1:909338243765:ios:f723c658bca357b42784fc',
    messagingSenderId: '909338243765',
    projectId: 'matsuyama-web',
    storageBucket: 'matsuyama-web.appspot.com',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtosuqCL942JB_Zeg40iCLnUCPJiUhL4',
    appId: '1:909338243765:ios:338c053908a47d372784fc',
    messagingSenderId: '909338243765',
    projectId: 'matsuyama-web',
    storageBucket: 'matsuyama-web.appspot.com',
    iosBundleId: 'com.example.webApp.RunnerTests',
  );
}
